### PR TITLE
client - default_character_set - use DB_DEFAULT_CHARACTER_SET

### PR DESCRIPTION
**Pull request by jhult**
Use `DB_DEFAULT_CHARACTER_SET` variable instead of hard-coding `UTF8`.

This may help with issue #217.

### CODE REVIEW

**Comment by Mauraza** [comment]
Hi @jhult,

The character can change following this part of the README.md https://github.com/bitnami/bitnami-docker-mariadb/#setting-character-set-and-collation

**Comment by jhult** [comment]
@Mauraza, I understand that. However, this is to ensure the variable `DB_DEFAULT_CHARACTER_SET` is used instead of hard-coding `utf8`.

**Review by Mauraza — CHANGES_REQUESTED** [review]
Hi @jhult,

You need to add the new variable `DB_DEFAULT_CHARACTER_SET` to the files `mariadb-env.sh` with the default value.

**Comment by jhult** [comment]
`DB_DEFAULT_CHARACTER_SET`  already exists in [mariadb-env.sh](https://github.com/bitnami/bitnami-docker-mariadb/blob/c94df5424d37f90466702599acf77a6de5739c4a/10.6/debian-10/rootfs/opt/bitnami/scripts/mariadb-env.sh#L90).

The server [uses](https://github.com/bitnami/bitnami-docker-mariadb/blob/da96f0a42570debcd0d93fb1a67f104ec04ce886/10.6/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L156) `DB_DEFAULT_CHARACTER_SET`:

```
[mysqld]
...
character_set_server=${DB_DEFAULT_CHARACTER_SET}
...
```

The client [does not](https://github.com/bitnami/bitnami-docker-mariadb/blob/da96f0a42570debcd0d93fb1a67f104ec04ce886/10.6/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L163) (which is the issue):
```
[client]
...
default_character_set=UTF8
...
```

**Comment by rafariossaa** [comment]
LGTM

**Pull request merged**
