### PR TITLE
Stacksmith merger

### PR DESCRIPTION
**Pull request by sameersbn**

### CODE REVIEW

**Comment by sameersbn** [comment]
retest this please

**Comment by sameersbn** [comment]
test this please

**Comment by prydonius** [comment]
retest this please

**Comment by sameersbn** [comment]
retest this please

**Comment by sameersbn** [comment]
retest this please

**Comment by sameersbn** [comment]
retest this please

**Comment by prydonius** [comment]
🎉  :tada: :tada:

**Pull request merged**
