### PR TITLE
Add support for docker secretes files to passed as environment variables

### PR DESCRIPTION
**Pull request by milis92**
**Description of the change**

Extracts secretes from files and exports them to environment variables

**Benefits**

Users will be able to pass secret files instead of plain passwords when starting this container

**Additional information**

Maybe `extract_from_file` function should be added to the base image for future use in all images

### CODE REVIEW

**Comment by jbgraindorge** [comment]
Any chance to have this merged ?

**Comment by tompizmor** [comment]
@f0restgump92 could you please add an example of how would you use this feature? Also, this is just for the swarm mode of Docker right?

**Comment by f0restgump92** [comment]
@tompizmor This is for all modes. I've tested this with compose, rancher and normal mode (but it should work for the rest). It basically allows users to pass docker secret files instead of plain variables.

For example if you want to pass MARIADB_PASSWORD variable, but you don't want it to be exposed on on your cli or in your Ci logs, you can create a [docker secret](https://docs.docker.com/engine/swarm/secrets/) and pass file path instead.

In order to pass MARIADB_PASSWORD as file, first you have to create docker secret with your password, and that pass it as MARIADB_PASSWORD_FILE variable. `extract_from_file` function will export passed variable to MARIADB_PASSWORD env var.

Users can pass either:

`MARIADB_MASTER_ROOT_USER` or `MARIADB_MASTER_ROOT_USER_FILE`
`MARIADB_MASTER_ROOT_PASSWORD` or `MARIADB_MASTER_ROOT_PASSWORD_FILE`
`MARIADB_REPLICATION_USER` or `MARIADB_REPLICATION_USER_FILE`
`MARIADB_REPLICATION_PASSWORD` or `MARIADB_REPLICATION_PASSWORD_FILE`
`MARIADB_USER` or `MARIADB_USER_FILE`
`MARIADB_PASSWORD` or `MARIADB_PASSWORD_FILE`

**Comment by tompizmor** [comment]
@f0restgump92 Thanks for the explanation and the example. However, when I try to create a docker secret in normal mode I get this error:

```
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
``` 
That is why I thought it only applied to swarm mode.

Furthermore, we will need to evaluate this PR internally to check if this is a feature that we want to add and maintain in our containers.

**Comment by f0restgump92** [comment]
@tompizmor Sorry for late reply... Yeah this is not going to work with normal mode actually, but its supper popular solution when it comes to docker-compose/swarm modes.

**Comment by tompizmor** [comment]
Hi, @f0restgump92! 
Thanks again for this PR! We will probably add this feature to our containers but we want to do it in a way that is more reusable that edit each container (Probably a function in the base image or similar). Unfortunately, we don't have the capacity now to work on this so I cannot provide you with a specific ETA.

**Comment by f0restgump92** [comment]
@tompizmor Awesome, even better, once again thank you for awesome images

**Pull request closed without merging**
